# Generated by Django 3.2.18 on 2023-05-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetails',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(max_length=255, unique='True', verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='sub_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectmodules', verbose_name='Subject Modules'),
        ),
    ]
