# Generated by Django 3.2.18 on 2023-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230503_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='subjectdetails',
            name='sub_cont',
            field=models.TextField(verbose_name='Subject Content'),
        ),
    ]
