# Generated by Django 3.2.18 on 2023-05-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230516_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=250)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Subject Name')),
            ],
        ),
    ]
